/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.BuyerMgt;

import Business.Buyer;
import Business.Wine;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author raywa
 */
public class buyerViewWineDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form buyerViewWineDetailPanel
     */
    private JPanel processPanel;
    private Wine w;

    public buyerViewWineDetailPanel(JPanel processPanel, Wine w) {
        initComponents();
        this.processPanel = processPanel;
        this.w = w;
        //show the details in the textbox;
        txtWineName.setText(w.getWineName());
        txtWinePrice.setText(String.valueOf(w.getPrice()));
        txtNumberOfProduct.setText(String.valueOf(w.getNumberofInventory()));
        txtLocation.setText(w.getLocation());
        txtAlcohol.setText(String.valueOf(w.getAlcoholPercentage()));
        txtCountry.setText(w.getOriginCountry());
        txtGrape.setText(w.getGrape());
        txtSellerName.setText(w.getSeller().getFirstName() + " " + w.getSeller().getLastName());
    }

    buyerViewWineDetailPanel(JPanel processPanel, Buyer buyer) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumberOfProduct = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGrape = new javax.swing.JTextField();
        txtWineName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtAlcohol = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chkPrime = new javax.swing.JCheckBox();
        txtWinePrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        btnBacktoCart = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnBacktoOrder = new javax.swing.JButton();
        btnBacktoProducts = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSellerName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rage Italic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("View Detail of a Wine");

        txtNumberOfProduct.setEnabled(false);
        txtNumberOfProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfProductActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("Type of Grape:");

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Wine Name:");

        txtGrape.setEnabled(false);

        txtWineName.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 102, 102));
        jLabel24.setText("Location of Product (State):");

        jLabel10.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("Alcohol%");

        txtLocation.setEnabled(false);

        txtAlcohol.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Prime?");
        jLabel9.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("Price:");

        chkPrime.setEnabled(false);

        txtWinePrice.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("Origin Country:");

        txtCountry.setEnabled(false);

        btnBacktoCart.setBackground(new java.awt.Color(255, 255, 255));
        btnBacktoCart.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnBacktoCart.setForeground(new java.awt.Color(255, 102, 102));
        btnBacktoCart.setText("Back to cart");
        btnBacktoCart.setEnabled(false);
        btnBacktoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktoCartActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 102));
        jLabel18.setText("Number of Product:");

        btnBacktoOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnBacktoOrder.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnBacktoOrder.setForeground(new java.awt.Color(255, 102, 102));
        btnBacktoOrder.setText("Back to order Histroy");
        btnBacktoOrder.setEnabled(false);
        btnBacktoOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktoOrderActionPerformed(evt);
            }
        });

        btnBacktoProducts.setBackground(new java.awt.Color(255, 255, 255));
        btnBacktoProducts.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnBacktoProducts.setForeground(new java.awt.Color(255, 102, 102));
        btnBacktoProducts.setText("Back to browse products");
        btnBacktoProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktoProductsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Seller Name:");

        txtSellerName.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBacktoProducts)
                            .addGap(51, 51, 51)
                            .addComponent(btnBacktoCart)
                            .addGap(54, 54, 54)
                            .addComponent(btnBacktoOrder))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNumberOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(246, 246, 246)
                                        .addComponent(txtGrape, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtWinePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(246, 246, 246)
                                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtWineName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(246, 246, 246)
                                        .addComponent(txtAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel24))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(98, 98, 98)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel2)))
                                            .addComponent(chkPrime))))
                                .addGap(18, 18, 18)
                                .addComponent(txtSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtGrape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtWineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtWinePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumberOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(chkPrime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBacktoProducts)
                    .addComponent(btnBacktoCart)
                    .addComponent(btnBacktoOrder))
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBacktoProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoProductsActionPerformed
        // TODO add your handling code here:
        /*Component[] componentArray = processPanel.getComponents();
        Component comp = componentArray[componentArray.length - 1];
        //just remove this panel;
        JPanel browseproductpPanel = (JPanel) comp;
        CardLayout card = (CardLayout) processPanel.getLayout();
        card.previous(processPanel);*/
        
        //Feb 27--修改了此处的跳转，之前似乎是没有关闭过这个面板导致此面板无法initial；
        processPanel.remove(this);
        Component[] componentArray = processPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        buyerStartPanel buyerPanel = (buyerStartPanel) component;
        buyerPanel.refreshTable();
        CardLayout layout = (CardLayout) processPanel.getLayout();
        layout.previous(processPanel);
        //buyerTabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_btnBacktoProductsActionPerformed

    private void btnBacktoOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoOrderActionPerformed
        // TODO add your handling code here:
        Component[] componentArray = processPanel.getComponents();
        Component comp = componentArray[componentArray.length - 1];
        JPanel myorderPanel = (JPanel) comp;
        CardLayout card = (CardLayout) processPanel.getLayout();
        card.previous(processPanel);
    }//GEN-LAST:event_btnBacktoOrderActionPerformed

    private void btnBacktoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoCartActionPerformed
        // TODO add your handling code here:
        Component[] componentArray = processPanel.getComponents();
        Component comp = componentArray[componentArray.length - 1];
        //We need to change the code here, need to find a function to control to jump to the right pad;
        //UserTabPane.setSelectedIndex(1);
        JPanel mycarPanel = (JPanel) comp;
        CardLayout card = (CardLayout) processPanel.getLayout();
        card.previous(processPanel);
        txtWineName.setText("");
        txtWinePrice.setText("");
        txtNumberOfProduct.setText("");
        txtLocation.setText("");
        txtAlcohol.setText("");
        txtCountry.setText("");
        txtGrape.setText("");
        txtSellerName.setText("");
    }//GEN-LAST:event_btnBacktoCartActionPerformed

    private void txtNumberOfProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacktoCart;
    private javax.swing.JButton btnBacktoOrder;
    private javax.swing.JButton btnBacktoProducts;
    private javax.swing.JCheckBox chkPrime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAlcohol;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtGrape;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtNumberOfProduct;
    private javax.swing.JTextField txtSellerName;
    private javax.swing.JTextField txtWineName;
    private javax.swing.JTextField txtWinePrice;
    // End of variables declaration//GEN-END:variables
}
