/*
Author: Ruifeng Wang
Date: 02/14/2018
The firstpage serves as the first start up page of the application, because we can't use card layout to jump back to a mainJFrame,
we are using the firstPage as the start. All the necessary classes are declared in this panel, as well as the login function
this page will also guide users to the create seller and create buyer panels. 

If the user logs in sccessfully, the application will take the user to he corresponding screen, based on the role of that user
 */
package Interface;

import Business.*;
import javax.swing.JOptionPane;
import Interface.BuyerMgt.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Interface.SellerMgt.*;

public class firstPage extends javax.swing.JPanel {

    private Business business;
    private JPanel processPanel;
    private ConfigureBusiness cb;

    public firstPage(JPanel processPanel) {
        initComponents();
        business = business.getInstance();
        this.processPanel = processPanel;
        cb = new ConfigureBusiness(business);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCreateBuyerAccount = new javax.swing.JButton();
        btnCreateSellerAccount = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Rage Italic", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Morning Wine LLC.");

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("User Name:");

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Password:");

        btnLogin.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 102, 102));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Don't have an account yet? Sign up within 1 minute!");

        btnCreateBuyerAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateBuyerAccount.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnCreateBuyerAccount.setForeground(new java.awt.Color(255, 102, 102));
        btnCreateBuyerAccount.setText("Buyer");
        btnCreateBuyerAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBuyerAccountActionPerformed(evt);
            }
        });

        btnCreateSellerAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateSellerAccount.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnCreateSellerAccount.setForeground(new java.awt.Color(255, 102, 102));
        btnCreateSellerAccount.setText("Seller");
        btnCreateSellerAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSellerAccountActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("I am a:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateSellerAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateBuyerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)
                        .addComponent(btnCreateSellerAccount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnCreateBuyerAccount)))
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    // login function fully functional
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (txtUser.getText().equals("") || txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter both user name and password");
            return;
        }
        String userName = txtUser.getText();
        String password = txtPassword.getText();
        boolean flag = false;
        for (Account a : business.getAd().getAccountList()) {
            if (a.getUserName().equals(userName) && a.getPassword().equals(password)) {
                if (a.getRole().equals(Account.BUYER)) {
                    buyerStartPanel bsp = new buyerStartPanel(processPanel, (Buyer) a.getPerson(), business);
                    processPanel.add("buyerStartPanel", bsp);
                    CardLayout card = (CardLayout) processPanel.getLayout();
                    card.next(processPanel);
                    flag = true;
                    break;
                } else if (a.getRole().equals(Account.SELLER)) {
                    sellerStartPanel ssp = new sellerStartPanel(processPanel, (Seller) a.getPerson(), business);
                    processPanel.add("sellerStartPanel", ssp);
                    CardLayout card = (CardLayout) processPanel.getLayout();
                    card.next(processPanel);
                    flag = true;
                    break;
                }
            }
        }
        if (flag == false) {
            JOptionPane.showMessageDialog(null, "No user account exists or the password is wrong");
            return;
        }
        txtUser.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCreateBuyerAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBuyerAccountActionPerformed
        // TODO add your handling code here:
        createBuyerPanel cbp = new createBuyerPanel(processPanel, business);
        processPanel.add("createBuyerPanel", cbp);
        CardLayout card = (CardLayout) processPanel.getLayout();
        card.next(processPanel);
    }//GEN-LAST:event_btnCreateBuyerAccountActionPerformed

    private void btnCreateSellerAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSellerAccountActionPerformed
        // TODO add your handling code here:
        createSellerPanel csp = new createSellerPanel(processPanel, business);
        processPanel.add("createSellerPanel", csp);
        CardLayout card = (CardLayout) processPanel.getLayout();
        card.next(processPanel);
    }//GEN-LAST:event_btnCreateSellerAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBuyerAccount;
    private javax.swing.JButton btnCreateSellerAccount;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
